### ISSUE TITLE
我在materialApp的 home属性注册后，退出登录重新登录后，调用报错

### ISSUE THREAD

**Issue by master950** [ifgyong/flutter_easyHub#3]
我调用 pushAndRemoveUntil, 清空路由栈其他页面，跳转登陆页面，结果登陆的时候调用方法提示Looking up a deactivated widget's ancestor is unsafe. 
![image](https://user-images.githubusercontent.com/32058233/89880117-733c7080-dbf6-11ea-8cc9-23e5c6ed764e.png)

**Comment by ifgyong** [comment]
需要在每个`Route`初始化的时候分别调用的。因为需要记录每个`context`才能给他弹窗

**Comment by ifgyong** [comment]
如果弹窗不在当前页面，请在调用前显示指定`context`.

**Comment by master950** [comment]
嗯嗯，谢谢大大的及时回复

**Comment by chuguofei** [comment]
flutter_boost 无法使用

**Comment by ifgyong** [comment]
> flutter_boost 无法使用

请问 具体代码是什么？
