### ISSUE TITLE
背景颜色渐变动画

### ISSUE THREAD

**Issue by 623637646** [ifgyong/flutter_easyHub#4]
很喜欢这个库。有个小问题，灰色半透明背景是没有渐变动画的，看起来很突兀。不知道能否加上。

**Comment by ifgyong** [comment]
ok 下期 搞上去。

**Comment by ifgyong** [comment]
> 很喜欢这个库。有个小问题，灰色半透明背景是没有渐变动画的，看起来很突兀。不知道能否加上。

1.0.2  已解决。暂时关闭了，有需求可以再提😄
